name: release npm package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          always-auth: true

      - name: install dependencies
        run: yarn install

      - name: build
        run: yarn build

      - name: publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
